apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: project/name
                    operator: In
                    values:
                      - roboshop
      topologySpreadConstraints:
        - topologyKey: kubernetes.io/hostname
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: {{ .Values.appName }}
      containers:
        - name: {{ .Values.appName }}
          image: prashumps.azurecr.io/prashumps-{{ .Values.appName }}:{{ .Values.appTag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.appName }}
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory | default "64Mi" }}"
              cpu: "{{ .Values.resources.requests.cpu | default "30m" }}"
            limits:
              memory: "{{ .Values.resources.limits.memory | default "128Mi" }}"
              cpu: "{{ .Values.resources.limits.cpu | default "100m" }}"
